# Generated by Django 5.2.3 on 2025-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon class or URL (e.g., 'fa-brands fa-docker' or SVG path)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description or tagline",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon class or URL (e.g., 'fa-brands fa-python' or SVG path)",
                        max_length=100,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Proficiency from 1 to 100"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Hex color for progress bar (e.g., #2563eb for blue)",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["start_date"]},
        ),
    ]
